name: Tests

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install packages
        run: yarn install --immutable

      - name: Run npmluau
        run: yarn run prepare

      - name: Run linter
        # lint only with selene for now, because luau-lsp can't ignore errors in node_modules
        run: yarn run lint:selene

      - name: Verify code style
        run: yarn run style-check

      - name: Build assets
        run: yarn run build
